version: "3.8"

services:
  images-server:
    image: nginx:latest
    container_name: images_server
    volumes:
      - ./images:/usr/share/nginx/html:ro
      - ./nginx/images.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy_server
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
    ports:
      - "8083:80"

volumes:
  nginx_cache: