services:

  mongo:
    image: mongo:8.0
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: always
    networks:
      - backend

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    user: root:1000
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/?authSource=admin
    volumes:
      - mongo_data:/data/db
    ports:
      - "9081:8081"
    depends_on:
      - mongo
    networks:
      - backend

  app:
    image: stress-testing-demo
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      - ConnectionStrings__MongoDb=mongodb://root:example@mongo:27017
    networks:
      - backend
    depends_on:
      - mongo

volumes:
  mongo_data: {}
  mongo_config: {}

networks:
  backend:
    driver: bridge
