services:
  postgres:
    image: postgres:15
    container_name: postgresql-b
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8G"
        reservations:
          cpus: "2"
          memory: "4G"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_shard1:
    image: postgres:15
    container_name: postgresql-b1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_1
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8G"
        reservations:
          cpus: "2"
          memory: "4G"
    volumes:
      - postgres_data_shard1:/var/lib/postgresql/data

  postgres_shard2:
    image: postgres:15
    container_name: postgresql-b2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_2
    ports:
      - "5434:5432"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8G"
        reservations:
          cpus: "2"
          memory: "4G"
    volumes:
      - postgres_data_shard2:/var/lib/postgresql/data 
      
volumes:
  postgres_data:
  postgres_data_shard1:
  postgres_data_shard2: