services:
  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - "11300:11300"

  redis-rdb:
    image: redis:latest
    container_name: redis-rdb
    command: ["redis-server", "--save", "60 1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis_rdb_data:/data

  redis-aof:
    image: redis:latest
    container_name: redis-aof
    command: ["redis-server", "--port", "6380", "--appendonly", "yes", "--loglevel", "warning"]
    ports:
      - "6380:6380"
    volumes:
      - redis_aof_data:/data

  influxdb:
    image: influxdb:1.11.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      retries: 5

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    links:
      - influxdb
      - redis-rdb
      - redis-aof
      - beanstalkd

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  redis_rdb_data:
  redis_aof_data:
  influxdb_data:
  grafana_data: