services:
  mysql:
    image: mysql:8.0.34
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prjctr
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: prjctr
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postges:/docker-entrypoint-initdb.d


volumes:
  mysql: {}
  postgres: {}
