name: Docker Image CI

on:
  push:
    branches: [ "03-monitoring-user-metrics" ]
  pull_request:
    branches: [ "03-monitoring-user-metrics" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          cd 03.Monitoring-user-metrics/currency-worker
          IMAGE_TAG=$(date +%s)
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Tag the Docker image as latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:latest

      - name: Push the Docker image with versioned tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:${{ env.IMAGE_TAG }}

      - name: Push the Docker image with latest tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:latest
