name: Run 03.Monitoring User Metrics Worker Every Hour

on:
  schedule:
    - cron: "0 * * * *" 

jobs:
  run-docker-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:latest

      - name: Run Docker Container
        run: docker run -e GA_MEASUREMENT_ID=${{ secrets.GA_MEASUREMENT_ID }} GA_API_SECRET=${{ secrets.GA_API_SECRET }}  ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:latest
