name: Run Docker Worker Every Hour

on:
  schedule:
    - cron: "*/10 * * * *" 

jobs:
  run-docker-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:latest

      - name: Run Docker Container
        run: docker run ${{ secrets.DOCKER_USERNAME }}/03.monitoring-user-metrics:latest