name: CI/CD for 10.NoSql-Elasticsearch

on:
  push:
    branches:
      - hw23
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
        ports:
          - 9200:9200
        options: >-
          --env discovery.type=single-node
          --env ES_JAVA_OPTS="-Xms512m -Xmx512m"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Wait for Elasticsearch to be ready
      run: |
        for i in {1..30}; do
          curl -s http://localhost:9200/_cluster/health | grep '"status":"green"' && break
          echo "Waiting for Elasticsearch to be ready..."
          sleep 2
        done

    - name: Install dependencies
      working-directory: 10.NoSql-Elasticsearch
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      working-directory: 10.NoSql-Elasticsearch
      run: python -m unittest discover -s . -p "test_*.py"

    - name: Run acceptance tests
      working-directory: 10.NoSql-Elasticsearch
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Dummy deploy step
      run: echo "Deployment successful!"
