name: Run Tests for 10.NoSql-Elasticsearch

on:
  push:
    branches:
      - hw23
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          xpack.security.enabled: false
        options: >-
          --health-cmd="curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=12
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms256m -Xmx256m"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Verify Elasticsearch Health
      run: |
        curl -X GET "http://localhost:9200/_cluster/health?pretty"

    - name: Install dependencies
      working-directory: 10.NoSql-Elasticsearch
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      working-directory: 10.NoSql-Elasticsearch
      run: python -m unittest discover -s . -p "test_*.py"

    - name: Run acceptance tests
      working-directory: 10.NoSql-Elasticsearch
      run: pytest
